In [1]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv('Casino.csv')
df

,Fiscal Year,Month Ending,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
0,2021/22,06/30/2022 12:00:00 AM,Mohegan Tribe On-Reservation,379023,335505,5,43513,6390,6390,37123,6682
1,2021/22,06/30/2022 12:00:00 AM,MPTN On-Reservation,671843,685886,3,-14046,29041,0,-14046,0
2,2021/22,06/30/2022 12:00:00 AM,"MPI Master Wagering License CT, LLC",420056291,406814933,164727,13076631,12372142,3269158,9807473,1765345
3,2021/22,06/30/2022 12:00:00 AM,"Mohegan Digital, LLC",254393582,246515856,11645,7866081,1397441,1397441,6468640,1164355
4,2021/22,05/31/2022 12:00:00 AM,Mohegan Tribe On-Reservation,716607,681306,0,35301,4130,4130,31171,5611
...,...,...,...,...,...,...,...,...,...,...,...
138,2024/25,08/31/2024 12:00:00 AM,"Mohegan Digital, LLC",552906853,532307920,468730,20130203,4098131,3019530,17110672,3079921
139,2024/25,07/31/2024 12:00:00 AM,Mohegan Tribe On-Reservation,3543119,3410769,132,132219,20758,19833,112386,20229
140,2024/25,07/31/2024 12:00:00 AM,MPTN On-Reservation,3199509,3072580,265,126663,15071,15071,111592,20087
141,2024/25,07/31/2024 12:00:00 AM,"MPI Master Wagering License CT, LLC",692210181,668971512,697914,22540755,4284383,3381113,19159642,3448735
142,2024/25,07/31/2024 12:00:00 AM,"Mohegan Digital, LLC",535796500,516077716,561709,19157075,4411186,2873561,16283514,2931033

### 'drop' command is used to drop certain rows or columns. 'inplace' changes the original table.
### Axis 0 refers to the rows. 
### Axis 1 refers to the columns.

In [82]:
df.drop('Month Ending',axis=1, inplace=True)
df

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
0,2021/22,Mohegan Tribe On-Reservation,379023,335505,5,43513,6390,6390,37123,6682
1,2021/22,MPTN On-Reservation,671843,685886,3,-14046,29041,0,-14046,0
2,2021/22,"MPI Master Wagering License CT, LLC",420056291,406814933,164727,13076631,12372142,3269158,9807473,1765345
3,2021/22,"Mohegan Digital, LLC",254393582,246515856,11645,7866081,1397441,1397441,6468640,1164355
4,2021/22,Mohegan Tribe On-Reservation,716607,681306,0,35301,4130,4130,31171,5611
...,...,...,...,...,...,...,...,...,...,...
138,2024/25,"Mohegan Digital, LLC",552906853,532307920,468730,20130203,4098131,3019530,17110672,3079921
139,2024/25,Mohegan Tribe On-Reservation,3543119,3410769,132,132219,20758,19833,112386,20229
140,2024/25,MPTN On-Reservation,3199509,3072580,265,126663,15071,15071,111592,20087
141,2024/25,"MPI Master Wagering License CT, LLC",692210181,668971512,697914,22540755,4284383,3381113,19159642,3448735
142,2024/25,"Mohegan Digital, LLC",535796500,516077716,561709,19157075,4411186,2873561,16283514,2931033

### Using head and tail commands to check first and last entries of the dataset:

### 'tail' and 'head' functions dy default print the last or first 5 entries. This can be changed by specifying another number in parentheses.

In [83]:
df.head(3)

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
0,2021/22,Mohegan Tribe On-Reservation,379023,335505,5,43513,6390,6390,37123,6682
1,2021/22,MPTN On-Reservation,671843,685886,3,-14046,29041,0,-14046,0
2,2021/22,"MPI Master Wagering License CT, LLC",420056291,406814933,164727,13076631,12372142,3269158,9807473,1765345

In [84]:
df.tail()

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
138,2024/25,"Mohegan Digital, LLC",552906853,532307920,468730,20130203,4098131,3019530,17110672,3079921
139,2024/25,Mohegan Tribe On-Reservation,3543119,3410769,132,132219,20758,19833,112386,20229
140,2024/25,MPTN On-Reservation,3199509,3072580,265,126663,15071,15071,111592,20087
141,2024/25,"MPI Master Wagering License CT, LLC",692210181,668971512,697914,22540755,4284383,3381113,19159642,3448735
142,2024/25,"Mohegan Digital, LLC",535796500,516077716,561709,19157075,4411186,2873561,16283514,2931033

### The pd.set_option command is to set viewing preferences for a dataframe. It remembers these settings and applies them globally.

In [85]:
pd.set_option('display.max_columns', None)

In [86]:
df

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
0,2021/22,Mohegan Tribe On-Reservation,379023,335505,5,43513,6390,6390,37123,6682
1,2021/22,MPTN On-Reservation,671843,685886,3,-14046,29041,0,-14046,0
2,2021/22,"MPI Master Wagering License CT, LLC",420056291,406814933,164727,13076631,12372142,3269158,9807473,1765345
3,2021/22,"Mohegan Digital, LLC",254393582,246515856,11645,7866081,1397441,1397441,6468640,1164355
4,2021/22,Mohegan Tribe On-Reservation,716607,681306,0,35301,4130,4130,31171,5611
...,...,...,...,...,...,...,...,...,...,...
138,2024/25,"Mohegan Digital, LLC",552906853,532307920,468730,20130203,4098131,3019530,17110672,3079921
139,2024/25,Mohegan Tribe On-Reservation,3543119,3410769,132,132219,20758,19833,112386,20229
140,2024/25,MPTN On-Reservation,3199509,3072580,265,126663,15071,15071,111592,20087
141,2024/25,"MPI Master Wagering License CT, LLC",692210181,668971512,697914,22540755,4284383,3381113,19159642,3448735
142,2024/25,"Mohegan Digital, LLC",535796500,516077716,561709,19157075,4411186,2873561,16283514,2931033

### 'loc' and 'iloc' commands can both be used to access multiple entries, while 'at' and 'iat' can only access a single value.
### 'loc' and 'at' access using row & column *labels*, while 'iloc' and 'iat' access using row and column *indices*.

In [87]:
df.loc[4,'Patron Winnings']=199902
df

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers,Online Casino Gaming Win/(Loss),Promotional Coupons or Credits Wagered (3),Promotional Deduction (4),Total Gross Gaming Revenue,Payment (5)
0,2021/22,Mohegan Tribe On-Reservation,379023,335505,5,43513,6390,6390,37123,6682
1,2021/22,MPTN On-Reservation,671843,685886,3,-14046,29041,0,-14046,0
2,2021/22,"MPI Master Wagering License CT, LLC",420056291,406814933,164727,13076631,12372142,3269158,9807473,1765345
3,2021/22,"Mohegan Digital, LLC",254393582,246515856,11645,7866081,1397441,1397441,6468640,1164355
4,2021/22,Mohegan Tribe On-Reservation,716607,199902,0,35301,4130,4130,31171,5611
...,...,...,...,...,...,...,...,...,...,...
138,2024/25,"Mohegan Digital, LLC",552906853,532307920,468730,20130203,4098131,3019530,17110672,3079921
139,2024/25,Mohegan Tribe On-Reservation,3543119,3410769,132,132219,20758,19833,112386,20229
140,2024/25,MPTN On-Reservation,3199509,3072580,265,126663,15071,15071,111592,20087
141,2024/25,"MPI Master Wagering License CT, LLC",692210181,668971512,697914,22540755,4284383,3381113,19159642,3448735
142,2024/25,"Mohegan Digital, LLC",535796500,516077716,561709,19157075,4411186,2873561,16283514,2931033

In [88]:
print(df.iat[3,5])

7866081

In [95]:
df.loc[1:4,['Fiscal Year', 'Patron Winnings', 'Cancelled Wagers']]

  Fiscal Year  Patron Winnings  Cancelled Wagers
1     2021/22           685886                 3
2     2021/22        406814933            164727
3     2021/22        246515856             11645
4     2021/22           199902                 0

In [104]:
df.loc[1:7,['Promotional Deduction (4)','Payment (5)']]

   Promotional Deduction (4)  Payment (5)
1                          0            0
2                    3269158      1765345
3                    1397441      1164355
4                       4130         5611
5                       6568         3546
6                    3122574      1686190
7                    1205520      1288297

In [106]:
df.iloc[3:5,1:5]

                       Licensee     Wagers  Patron Winnings  Cancelled Wagers
3          Mohegan Digital, LLC  254393582        246515856             11645
4  Mohegan Tribe On-Reservation     716607           199902                 0

### pivot and pivot_table are used to reshape/reconstruct tables.
### They can convert columns to rows and vice versa. 
### The difference is that pivot cannot handle duplicates, while pivot_table can. The aggregate function in pivot_table can be of multiple types like mean/sum etc to handle the duplicate values mentioned previously.

In [120]:
df2=df.iloc[0:5,0:5]
df2

,Fiscal Year,Licensee,Wagers,Patron Winnings,Cancelled Wagers
0,2021/22,Mohegan Tribe On-Reservation,379023,335505,5
1,2021/22,MPTN On-Reservation,671843,685886,3
2,2021/22,"MPI Master Wagering License CT, LLC",420056291,406814933,164727
3,2021/22,"Mohegan Digital, LLC",254393582,246515856,11645
4,2021/22,Mohegan Tribe On-Reservation,716607,199902,0

In [121]:
df2.pivot(columns= 'Fiscal Year')

,Licensee,Wagers,Patron Winnings,Cancelled Wagers
Fiscal Year,2021/22,2021/22,2021/22,2021/22
0,Mohegan Tribe On-Reservation,379023,335505,5
1,MPTN On-Reservation,671843,685886,3
2,"MPI Master Wagering License CT, LLC",420056291,406814933,164727
3,"Mohegan Digital, LLC",254393582,246515856,11645
4,Mohegan Tribe On-Reservation,716607,199902,0

### In the following example, pivot_table is used to handle duplicate value. I have used the sum function here, but other aggregate functions like mean can also be used.

In [124]:
df2.pivot_table(index='Licensee', columns= 'Fiscal Year',aggfunc='sum')

,Cancelled Wagers,Patron Winnings,Wagers
Fiscal Year,2021/22,2021/22,2021/22
Licensee,,,
"MPI Master Wagering License CT, LLC",164727,406814933,420056291
MPTN On-Reservation,3,685886,671843
"Mohegan Digital, LLC",11645,246515856,254393582
Mohegan Tribe On-Reservation,5,535407,1095630

## Pre-Processing Techniques:
Now for pre-processing techniques. I came across feature scaling, which is important primarily because a lot of algorithms like 'K-Means Clustering' rely on the Euclidean distance between two points. This Euclidean distance can become very large due to different units used to express magntitudes. For example: 
If height is expressed in cm, let's say 170 and 180cm respectively for two samples.
And if weight is expressed in kg, let's say 60 and 65kg respectively for two samples.
Then the corresponding data points become (170,60) and (180,65).

This means the Euclidean distance is pretty large. Why is this important? 
Well, because a lot of calculations like linear regressions become faster if Euclidean distances are smaller. In the case of linear regression, the convergence point is achieved much quicker if the values are scaled down because calculations become less intense.  
Also, CNN's take input as images whose pixel values can be between 0 to 255. To convert these into normalised ranges, techniques like normalisation can be used.

The most common library I come across is scikitlearn.preprocessing.

## Normalisation:

Normalisation is basically done to ensure all values are between 0 to 1. The maximum value becomes 1, while the minimum becomes 0.

How is this done?

The formula is: *x (normalised) = [x - x(min)]/ x(max) - x(min)*

## Standardisation:

It converts the entire distribution into a distribution with *Mean = 0* and *Standard Deviation = 1* . Note that it does NOT alter the table into a normalised bell curve, that is just a misconception- albeit a popular one.

## Imputation:

Imputation is used to fill out missing values from a dataset. It can be achieved using a variety of methods. We can calculate the mean of two points equidistant from it (before and after). Or we can also use ML models that predict the missing value based on other features for that record.

## Encoding Variables as Numbers:

A lot of times, values like 'high', 'medium' and 'low' can be encoded to 0,1,2 respectively to make operations easier. 
Further, NaN (Not a Number) values can be encountered in datasets to represent missing data. This data type cannot be operated upon, and so it makes sense to drop rows or columns if the number of NaN values in them are too high and/or these rows or columns are very less in comparison to the total dataset. We can also fill them with values like 0 or -1 to make calculations easier.  
Such operations are easily achievable by in-built PANDAS features like pd.dropna() or pd.fillna().